package com.example.demo.mock;

import com.example.demo.post.domain.Post;
import com.example.demo.post.service.port.PostRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * packageName : com.example.demo.mock
 * fileName    : FakePostRepository
 * author      : ckr
 * date        : 24. 9. 20.
 * description :
 */
public class FakePostRepository implements PostRepository {

    private long autoGeneratedId = 0L;
    private final List<Post> storedPosts = new ArrayList<>();

    @Override
    public Optional<Post> findById(long id) {
        return storedPosts.stream()
            .filter(storedPost -> storedPost.getId().equals(id))
            .findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null || post.getId() == 0L) {
            Post newPost = Post.builder()
                .id(autoGeneratedId++)
                .content(post.getContent())
                .createdAt(post.getCreatedAt())
                .modifiedAt(post.getModifiedAt())
                .writer(post.getWriter())
                .build();
            storedPosts.add(newPost);
            return newPost;
        } else {
            storedPosts.removeIf(storedPost -> storedPost.getId().equals(post.getId()));
            storedPosts.add(post);
            return post;
        }
    }
}
